apiVersion: v2
name: trendai-sensor
description: Kubernetes node-level network sensor (eBPF capture, VXLAN forwarding).
type: application
version: 0.1.4
appVersion: "v0.1.4"
kubeVersion: ">=1.25.0-0"
home: https://github.com/felipecosta09/trendai-sensor
sources:
  - https://github.com/felipecosta09/trendai-sensor
keywords:
  - ebpf
  - network
  - security
  - sensor
  - ndr
  - vxlan
maintainers:
  - name: Felipe Costa
