apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "trendai-sensor.fullname" . }}
  namespace: {{ include "trendai-sensor.namespace" . }}
  labels:
    {{- include "trendai-sensor.labels" . | nindent 4 }}
